import type { NextConfig } from "next";
import crypto from "crypto";
import fs from "fs";
import path from "path";

const keyFile = path.resolve(process.cwd(), "lib/auth-keys.ts");
let generate = false;
try {
  const content = fs.readFileSync(keyFile, "utf-8");
  if (content.includes("GENERATE_ME")) generate = true;
} catch (e) {
  generate = true;
}

if (generate) {
  console.log("Generating Asymmetric RS256 Keypair for secure authentication...");
  const { privateKey, publicKey } = crypto.generateKeyPairSync("rsa", {
    modulusLength: 2048,
    publicKeyEncoding: { type: "spki", format: "pem" },
    privateKeyEncoding: { type: "pkcs8", format: "pem" }
  });

  // We export the keys directly into a TS file so Edge Middleware can bundle it seamlessly!
  const tsContent = `// Auto-generated by next.config.ts\nexport const AUTH_PRIVATE_KEY = \`${privateKey}\`;\nexport const AUTH_PUBLIC_KEY = \`${publicKey}\`;\n`;
  const dir = path.dirname(keyFile);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(keyFile, tsContent);
}

const nextConfig: NextConfig = {
  /* config options here */
};

export default nextConfig;
